version: '3'

services:
  mysql:
    image: sameersbn/mysql:5.7.22-1
    container_name: redmine_db
    env_file:
    - db_auth.env
    volumes:
    - mysql_data:/var/lib/mysql

  redmine:
    image: sameersbn/redmine:3.4.6
    container_name: redmine
    depends_on:
    - mysql
    env_file:
    - db_auth.env
    - redmine_mysql.env
    - redmine.env
    ports:
    - "10083:80"
    volumes:
    - redmine_data:/home/redmine/data

volumes:
  redmine_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
